
[Network]
  # The address of the server, including the port. The server will be listening on this address. If another
  # server is already running on this port, please select a different port.
  Address = ":19132"

[Server]
  # The name as it shows up in the server list. Minecraft colour codes may be used in this name to format the
  # name of the server.
  Name = "Dragonfly Server"
  # AuthEnabled controls whether players must be connected to Xbox Live in order to join the server.
  AuthEnabled = true
  # DisableJoinQuitMessages specifies if join/quit messages should be broadcast when players join the server.
  DisableJoinQuitMessages = false
  # MuteEmoteChat specifies if the player emote chat should be muted or not.
  MuteEmoteChat = false

[World]
  # The folder that the world files (will) reside in, relative to the working directory. If not currently
  # present, the folder will be made.
  Folder = "world"
  # Whether the worlds' data will be saved and loaded. If true, the server will use the
  # default LevelDB data provider and if false, an empty provider will be used. To use your
  # own provider, turn this value to false, as you will still be able to pass your own provider.
  SaveData = true

[Players]
  # The maximum amount of players accepted into the server. If set to 0, there is no player limit. The max
  # player count will increase as more players join.
  MaxCount = 0
  # The maximum chunk radius that players may set in their settings. If they try to set it above this number,
  # it will be capped and set to the max.
  MaximumChunkRadius = 32
  # Whether a player's data will be saved and loaded. If true, the server will use the
  # default LevelDB data provider and if false, an empty provider will be used. To use your
  # own provider, turn this value to false, as you will still be able to pass your own provider.
  SaveData = true
  # Folder controls where the player data will be stored by the default LevelDB
  # player provider if it is enabled.
  Folder = "players"

[Resources]
  # AutoBuildPack is if the server should automatically generate a resource pack for custom features.
  AutoBuildPack = true
  # Folder configures the directory used by the server to load resource packs.
  Folder = "resources"
  # Required configures whether the server will require players to have a resource pack to join.
  Required = true
